# Generated by Django 3.0.8 on 2021-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=200)),
                ('DOB', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
