# Generated by Django 3.0.8 on 2021-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleengine',
            name='base_price',
            field=models.IntegerField(default=5000),
        ),
    ]
