# Generated by Django 3.0.8 on 2021-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine_app', '0002_ruleengine_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleengine',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
